POST http://localhost:8080/events
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRleHR1c2VyQGdtYWlsLmNvbSIsImV4cCI6MTc0MDU1ODk2MSwidXNlcklkIjoxfQ.f9Gwofd1Bm4uNUo8DVsvzwqSFUYuGGUT1Na5OTwBSP0

{
    "name": "Test event!!!",
    "description": "A Test Event!!!",
    "location": "Test Location!!!!",
    "dateTime": "2025-02-01T15:30:30.000Z"
}
