POST http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRleHR1c2VyQGdtYWlsLmNvbSIsImV4cCI6MTc0MDU1OTEyMywidXNlcklkIjoxfQ.FT-XiFmtoRoZFgIH8xq-Bv9UaooPrkyDTISn5Gz1IOA